name: study_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.24.0"



dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.0
  dio: ^5.7.0
  like_button: ^2.0.4
  badges: ^2.0.1
  provider: ^6.0.2
  loading_animation_widget: ^1.1.0+3
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1 # google_fonts を dependencies に追加
  flutter_hooks: ^0.20.5 # dev_dependencies から移動
  persistent_bottom_nav_bar: ^6.2.1 # dev_dependencies から移動
  flutter_barcode_scanner: ^2.0.0
  go_router: ^6.0.0
  fl_chart: ^0.69.0 # dev_dependencies から移動
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  lottie: ^2.0.0
  google_sign_in: ^5.4.3
  camera: ^0.10.0
  permission_handler: ^10.2.0
  cached_network_image: ^3.4.1
  image_picker: ^0.8.4+4
  path_provider: ^2.0.9
  cloudinary_flutter: ^1.3.0
  cloudinary_url_gen: ^1.0.0
  flutter_image_compress: ^2.3.0
  envied: ^1.0.0
  http: ^1.2.2
  shared_preferences: ^2.3.3
  dropdown_button2: ^2.3.9
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  envied_generator: ^1.0.0
  build_runner: ^2.4.13
flutter:
  uses-material-design: true

  assets:
    - assets/images/default_avatar.png
    - assets/animation/loading.json
    - assets/animation/success.json
    - assets/images/google_logo.png
    - assets/images/default_book_img.jpg

    