name: study_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.0
  badges: ^2.0.1
  provider: ^6.0.2
  loading_animation_widget: ^1.1.0+3
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1 # google_fonts を dependencies に追加
  flutter_hooks: ^0.20.5 # dev_dependencies から移動
  persistent_bottom_nav_bar: ^6.2.1 # dev_dependencies から移動
  like_button: ^2.0.5 # dev_dependencies から移動
  fl_chart: ^0.69.0 # dev_dependencies から移動
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  lottie: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/default_avatar.png
    - assets/animation/loading.json
    - assets/animation/success.json